dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
install:
  - sudo apt-get install libgtest-dev
before_script: cd calculadora
script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2

