dist: trusty
language: cpp
install: make get-gtest
addons:
    packages:
      - g++-5
before_script: cd calculadora
script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2

